name: My Github Action for testing and checking extra libs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET_KEY: AnyThingYouWant
      JWT_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 15
      REFRESH_TOKEN_EXPIRE_HOURS: 24
      SALT_LENGTH: 12

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -e ".[test,dev]"
          pip install -r requirements.txt
          pip install git+https://github.com/jeetendra29gupta/PyGatekeeper.git

      - name: Run Pytest
        run: pytest

      - name: Check formatting with black
        run: black --check .

      - name: Lint with flake8
        run: flake8 .

      - name: Run the updated Python script
        run: | 
          python main.py
          python check_extra_lib/main.py
